### ISSUE TITLE
Compatibility with Sublime Text 3

### ISSUE THREAD

**Issue by couto** [wukkuan/AMD-Module-Editor#1]
At this point the package doesn't seem to work with Sublime Text 3 Beta, at least on a MacOSX 10.7.5 computer

console output:

```
reloading plugin AMD Module Editor.amd_module_editor
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/couto/Library/Application Support/Sublime Text 3/Installed Packages/AMD Module Editor.sublime-package/amd_module_editor.py", line 52
    print action
               ^
SyntaxError: invalid syntax
reloading plugin AMD Module Editor.amd_module_list
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 72, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/couto/Library/Application Support/Sublime Text 3/Installed Packages/AMD Module Editor.sublime-package/amd_module_list.py", line 2, in <module>
ImportError: No module named 'cStringIO'
```

**Comment by wukkuan** [comment]
I hadn't tried it in ST3, yet. I'll work on it tonight. Thanks for the thorough error report.

That error is simple, I just need to change `print action` to `print(action)`. If the stars align, I should just be able to run the Python 2to3 tool over it to upgrade. I'll put the result in a new branch if it breaks ST2.

**Comment by wukkuan** [comment]
Fixed in st3 branch.
